// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lblarqxqhjipwotusyba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxibGFycXhxaGppcHdvdHVzeWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjUwMDAsImV4cCI6MjA3MzYwMTAwMH0.YdWddivKiC8yGMr4ixb2qzq47vCQVEBDbZ54DfZU6cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});